file = { stmt };
stmt = code_stmt | data_stmt | import_stmt | export_stmt | rep_stmt | endrep_stmt | label_stmt | loc_label_stmt | instruction_stmt | byte_stmt | word_stmt | dword_statement | qword_stmt | ascii_stmt | asciz_stmt
code_stmt = ".CODE", [ "(", ?TOKEN_IDENT?, ")"];
data_stmt = ".DATA", [ "(", ?TOKEN_IDENT?, ")"];
export_stmt = ".export", ?TOKEN_IDENT?;
import_stmt = ".import", ?TOKEN_IDENT?;
rep_stmt = ".rep", ?TOKEN_NUM?;
endrep_stmt = ".endrep";
label_stmt = ?TOKEN_IDENT?, ":"
loc_label_stmt = ".l", ?TOKEN_IDENT?, ":"

instruction_stmt = ?TOKEN_INSTR?, [ condition_code ], args, "\n";
condition_code = "(", ?TOKEN_COND_CODE?, ")";
args = [ arg, { ",", arg} ];
arg = ?TOKEN_REG? | ?TOKEN_SYS_REG? | ?TOKEN_ADDR_REG? | ?TOKEN_PORT? | immediate | label | loc_label;
immediate = "#", ?TOKEN_NUM? | ?TOKEN_CHAR?;
label = "=", ?TOKEN_IDENT?;
loc_label = direction_dir, "=", ?TOKEN_IDENT?;
direction_dir = ".f" | ".b";
loc_label_stmt = ".l", ?TOKEN_IDENT?, ":", "\n";

byte_stmt = "byte", ( ?TOKEN_NUM? | ?TOKEN_CHAR? );
word_stmt = "word", ( ?TOKEN_NUM? | ?TOKEN_CHAR? );
dword_stmt = "dword", ( ?TOKEN_NUM? | ?TOKEN_CHAR? );
qword_stmt = "qword", ( ?TOKEN_NUM? | ?TOKEN_CHAR? );
ascii_stmt = "ascii", ( ?TOKEN_ASCII? );
asciz_stmt = "asciz", ( ?TOKEN_ASCII? );
